### ISSUE TITLE
binder link/badge

### ISSUE THREAD

**Issue by betatim** [tpoisot/IntroScientificComputing#10]
I didn't see a binder badge in the README, we should fix that.

Not really a Julia expert but from what I can tell you have a `REQUIRE` file so this should just build on binder now right?

**Comment by tpoisot** [comment]
I use the link for each lesson in the table of content (instead of badges). But I can add the badge at the bottom if that's the binder "convention"!

**Comment by betatim** [comment]
[![Binder](https://beta.mybinder.org/badge.svg)](https://beta.mybinder.org/v2/gh/tpoisot/IntroScientificComputing/master)

**Comment by betatim** [comment]
Ah! I naively assumed the link in the TOC just linked inside the repo and didn't even hover it :)

**Comment by betatim** [comment]
That is so smart! Especially with directly opening the relevant notebook.

Maybe have a badge for old people 👴  like me :)

**Comment by tpoisot** [comment]
I'll make the behavior of the links more explicit (and add the badges!).
